name: Build and push docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      NODE_IMAGE: arm64v8/node:lts-alpine3.15
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull node image
        run: docker pull $NODE_IMAGE
      - 
        name: Set RELEASE_DATE
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          SB_IMAGE: kugaevsky/outline-server-arm64
        with:
          context: .
          file: src/shadowbox/docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: NODE_IMAGE=${{ env.NODE_IMAGE }}
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.SB_IMAGE }}:${{ env.RELEASE_DATE }}
            ${{ env.SB_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.SB_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.SB_IMAGE }}:buildcache,mode=max